import {
  useConfig,
  usePlayer,
  usePlayers,
  useAttemptsCount,
  useTimeToFreeAttempts,
  useBuyPoints,
  useAddPoints,
  useSetPlayerName,
  useBuyAttempt,
  useBuyBooster,
  useBuyShip,
  usePointsBalance,
  usePlayerNFT,
} from './hooks';

export {
  useConfig,
  usePlayer,
  usePlayers,
  useAttemptsCount,
  useTimeToFreeAttempts,
  useBuyPoints,
  useAddPoints,
  useSetPlayerName,
  useBuyAttempt,
  useBuyBooster,
  useBuyShip,
  usePointsBalance,
  usePlayerNFT,
};
