name: Build and Deploy Vara Starship

on:
  workflow_dispatch:
  push:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KUBECTL_VERSION: ${{ secrets.KUBECTL_VERSION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  KUBE_NAMESPACE: vara
  KUBE_DEPLOY_PREFIX: vara-starship
  KUBE_DEPLOY_TYPE: deployment # (statefulset or deployment)

jobs:
  prepair:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image.outputs.image_name }}
      environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect environment
        id: env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "environment=stg" >> $GITHUB_OUTPUT
          else
            echo "environment=none" >> $GITHUB_OUTPUT
          fi

      - name: Get branch
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "branch_name=$branch_name" >> $GITHUB_ENV

      - name: Get short SHA
        run: |
          sha_short=$(git rev-parse --short HEAD)
          echo "sha_short=$sha_short" >> $GITHUB_ENV

      - name: Set IMAGE_NAME
        id: image
        run: |
          image_name=${{ env.REGISTRY }}-${{ env.KUBE_DEPLOY_PREFIX }}:${{ env.branch_name }}-${{ env.sha_short }}
          echo "image_name=$image_name" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: [prepair]
    if: needs.prepair.outputs.environment != 'none'
    runs-on: ubuntu-latest
    environment: ${{ needs.prepair.outputs.environment }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          build-args: |
            VITE_CONTRACT_ADDRESS=${{ secrets.VITE_CONTRACT_ADDRESS }}
            VITE_NODE_ADDRESS=${{ secrets.VITE_NODE_ADDRESS }}
            VITE_NFT_SHOWROOM_ADDRESS=${{ secrets.VITE_NFT_SHOWROOM_ADDRESS }}
          tags: ${{ needs.prepair.outputs.image_name }}

  deploy-to-k8s:
    needs: [prepair, build-and-push-image]
    if: needs.prepair.outputs.environment != 'none'
    runs-on: ubuntu-latest
    environment: ${{ needs.prepair.outputs.environment }}
    steps:
      - name: Setup kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/${{ env.KUBECTL_VERSION }}/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          mkdir -p $HOME/.kube/
          echo "${{ env.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get containers
        id: containers
        run: |
          containers=$(kubectl get ${{ env.KUBE_DEPLOY_TYPE }}/${{ env.KUBE_DEPLOY_PREFIX }}-${{ needs.prepair.outputs.environment }} -n ${{ env.KUBE_NAMESPACE }} -o jsonpath="{.spec.template.spec.containers[*].name}")
          echo "CONTAINERS=$containers" >> $GITHUB_ENV

      - name: Update deployment image
        run: |
          for container in ${{ env.CONTAINERS }}; do
            kubectl set image ${{ env.KUBE_DEPLOY_TYPE }}/${{ env.KUBE_DEPLOY_PREFIX }}-${{ needs.prepair.outputs.environment }} $container=${{ needs.prepair.outputs.image_name }} -n ${{ env.KUBE_NAMESPACE }};
          done

      - name: Restart deployment
        run: |
          kubectl rollout restart ${{ env.KUBE_DEPLOY_TYPE }}/${{ env.KUBE_DEPLOY_PREFIX }}-${{ needs.prepair.outputs.environment }} -n ${{ env.KUBE_NAMESPACE }}

      - name: Check deployment
        run: |
          kubectl rollout status ${{ env.KUBE_DEPLOY_TYPE }}/${{ env.KUBE_DEPLOY_PREFIX }}-${{ needs.prepair.outputs.environment }} --timeout=300s -n ${{ env.KUBE_NAMESPACE }}
